# Generated by Django 4.0.5 on 2022-06-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
